# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comment.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

import application


class Ui_Form(QObject):
    #向teacherwindow传输text内容
    Comment_signal = pyqtSignal(list)
    def __init__(self, comment_id, app_type):
        super(Ui_Form, self).__init__()
        self.comment_id = comment_id
        self.app_type = app_type

    def setupUi(self, Form):
        self.form = Form
        Form.setObjectName("Form")
        Form.resize(563, 443)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comment_tx = QtWidgets.QTextEdit(Form)
        self.comment_tx.setObjectName("comment_tx")
        self.verticalLayout.addWidget(self.comment_tx)
        self.submit = QtWidgets.QPushButton(Form)
        self.submit.setObjectName("submit")
        self.verticalLayout.addWidget(self.submit)
        self.submit.clicked.connect(self.SendComment)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "评论"))
        self.submit.setText(_translate("Form", "提交"))

    def SendComment(self):
        appli = application.Manage_Application()
        comment_text = self.comment_tx.toPlainText()
        if (self.app_type == 'Agree'):
            appli.InsertCommentText(int(self.comment_id), comment_text, 'Passed')
        else:
            appli.InsertCommentText(int(self.comment_id), comment_text, 'Refused')
        self.Comment_signal.emit([comment_text, self.comment_id])
        self.form.hide()